# For Ubuntu platform only

sudo: true
language: cpp
os:
  - linux
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
env:
  - NODE_LABELS="Linux Ubuntu Ubuntu-12.04"
script:
  - ./.jenkins
